export const CUSTOMIZATION_CONFIG = {
  options: {
    title: "Options",
    settings: [
      {
        codename: "warning",
        name: "Warning",
        description: "All the written texts are demos for now",
        emoji: "warning",
        type: "action",
        defaultValue: null,
      },
      {
        codename: "reset_customization",
        name: "Reset Customization",
        description: "Reset all customization settings to default",
        emoji: "refresh",
        type: "action",
        defaultValue: null,
      },
      {
        codename: "import_export",
        name: "Import/Export",
        description: "Import or export customization settings",
        emoji: "import-export",
        type: "action",
        defaultValue: null,
      },
    ],
  },
  themes: {
    title: "Themes",
    settings: [
      {
        codename: "amoled_theme",
        name: "AMOLED Theme",
        description: "A neat black theme for OLED screens",
        emoji: "brush",
        type: "menu",
        defaultValue: null,
      },
      {
        codename: "white_mode",
        name: "White Mode",
        description: "A light theme for better visibility in sunlight",
        emoji: "brush",
        type: "menu",
        defaultValue: null,
      },
      {
        codename: "gray_theme",
        name: "Dark Theme",
        description: "A gray theme for a neutral look",
        emoji: "brush",
        type: "menu",
        defaultValue: null,
      },
    ],
  },
  colors: {
    title: "Colors",
    settings: [
      {
        codename: "wallpaper_accent",
        name: "Use wallpaper accent color",
        description:
          "Change the coloring based on the wallpaper colors (this'll disable everything underneath here)",
        emoji: "",
        type: "toggle",
        defaultValue: null,
      },
      {
        codename: "album_cover_accent",
        name: "Use album cover as accent color",
        description:
          "Change the coloring based on the album cover colors (this'll disable everything underneath here)",
        emoji: "",
        type: "toggle",
        defaultValue: null,
      },
      {
        codename: "primary_color",
        name: "Primary Color",
        description: "Set the accent color",
        emoji: "",
        type: "menu",
        defaultValue: null,
      },
      {
        codename: "secondary_color",
        name: "Secondary Color",
        description: "Set the secondary color",
        emoji: "",
        type: "menu",
        defaultValue: null,
      },
      {
        codename: "background_color",
        name: "Background Color",
        description: "Set the background color",
        emoji: "",
        type: "menu",
        defaultValue: null,
      },
      {
        codename: "navigation_color",
        name: "Navigation Color",
        description: "Set the navigation bar background color",
        emoji: "",
        type: "menu",
        defaultValue: null,
      },
    ],
  },
  views: {
    title: "Change how the app looks like",
    settings: [
      {
        codename: "fonts",
        name: "Fonts",
        description: "Change font related settings",
        emoji: "",
        type: "menu",
        defaultValue: null,
      },
      {
        codename: "border_radius",
        name: "Border Radius",
        description: "Change the border radius of elements",
        emoji: "",
        type: "menu",
        defaultValue: null,
      },
      {
        codename: "animations",
        name: "Animations",
        description: "Change the animations while navigating",
        emoji: "",
        type: "menu",
        defaultValue: null,
      },
      {
        codename: "nav_style",
        name: "Navigation Style",
        description: "Customize the style of the navigation bar",
        emoji: "",
        type: "menu",
        defaultValue: null,
      },
      {
        codename: "foryou_layout",
        name: "For You Layout",
        description: "Change the app logo with presets or custom images",
        emoji: "",
        type: "menu",
        defaultValue: null,
      },
      {
        codename: "tracks_layout",
        name: "Tracks Layout",
        description: "Change how the tracks are shown in the tracks page",
        emoji: "",
        type: "menu",
        defaultValue: null,
      },
      {
        codename: "playlists_style",
        name: "Playlists Style",
        description: "Change how the playlists are shown",
        emoji: "",
        type: "menu",
        defaultValue: null,
      },
      {
        codename: "discover_layout",
        name: "Discover Layout",
        description: "Change how the discover page is shown",
        emoji: "",
        type: "menu",
        defaultValue: null,
      },
    ],
  },
  app: {
    title: "App-related settings",
    settings: [
      {
        codename: "logo",
        name: "Logo",
        description: "Change the app logo with presets or custom images",
        emoji: "brush",
        type: "menu",
        defaultValue: null,
      },
      {
        codename: "name",
        name: "Name",
        description: "Change the app name as shown on the home screen",
        emoji: "brush",
        type: "menu",
        defaultValue: null,
      },
    ],
  },
};

export const CATEGORY_ICON_MAP: Record<string, string> = {
  options: "settings",
  themes: "palette",
  colors: "color-lens",
  views: "visibility",
  app: "apps"
};
