import { StyleSheet } from "react-native";

import { COLORS, RADIUS, SPACING, TYPOGRAPHY } from "../../constants/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.md,
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
  },
  searchButton: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  title: {
    fontFamily: "Inter_600SemiBold",
    ...TYPOGRAPHY.headlineLarge,
    fontWeight: "100",
    color: COLORS.onSurface,
    marginTop: 12,
    marginLeft: 27,
    marginBottom: 17,
  },
  headerActions: {
    flexDirection: "row",
    gap: SPACING.xs,
  },
  iconButton: {
    width: 48,
    height: 48,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.surfaceContainerHigh,
    justifyContent: "center",
    alignItems: "center",
  },
  searchWrapper: {
    overflow: "hidden",
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.surfaceContainerHigh,
    marginHorizontal: SPACING.md,
    marginBottom: SPACING.sm,
    borderRadius: RADIUS.xxl,
    paddingHorizontal: SPACING.md,
    height: 56,
    gap: SPACING.md,
  },
  searchInput: {
    flex: 1,
    fontFamily: "Inter_400Regular",
    ...TYPOGRAPHY.bodyLarge,
    color: COLORS.onSurface,
  },
  songCount: {
    fontFamily: "Inter_500Medium",
    ...TYPOGRAPHY.labelLarge,
    color: COLORS.onSurfaceVariant,
    paddingHorizontal: SPACING.md,
    display: "none",
    paddingVertical: SPACING.md,
  },
  listContent: {
    paddingHorizontal: SPACING.md,
    paddingBottom: 140,
  },
  emptyState: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 80,
  },
  emptyTitle: {
    fontFamily: "Inter_600SemiBold",
    ...TYPOGRAPHY.titleLarge,
    color: COLORS.onSurface,
    marginTop: SPACING.md,
  },
  emptyText: {
    fontFamily: "Inter_400Regular",
    ...TYPOGRAPHY.bodyMedium,
    color: COLORS.onSurfaceVariant,
    marginTop: SPACING.sm,
    textAlign: "center",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    justifyContent: "center",
    alignItems: "center",
    padding: SPACING.lg,
  },
  modalContent: {
    backgroundColor: COLORS.surfaceContainerHigh,
    borderRadius: RADIUS.xxl,
    padding: SPACING.lg,
    width: "100%",
    maxWidth: 400,
  },
  modalTitle: {
    fontFamily: "Inter_600SemiBold",
    ...TYPOGRAPHY.headlineSmall,
    color: COLORS.onSurface,
    marginBottom: SPACING.lg,
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.surfaceContainer,
    borderRadius: RADIUS.md,
    paddingHorizontal: SPACING.md,
    marginBottom: SPACING.md,
    gap: SPACING.md,
  },
  modalInput: {
    flex: 1,
    fontFamily: "Inter_400Regular",
    ...TYPOGRAPHY.bodyLarge,
    color: COLORS.onSurface,
    paddingVertical: SPACING.md,
  },
  modalActions: {
    flexDirection: "row",
    gap: SPACING.md,
    marginTop: SPACING.md,
  },
  modalButtonOutline: {
    flex: 1,
    height: 48,
    borderRadius: RADIUS.full,
    borderWidth: 1,
    borderColor: COLORS.outline,
    justifyContent: "center",
    alignItems: "center",
  },
  modalButtonOutlineText: {
    fontFamily: "Inter_500Medium",
    ...TYPOGRAPHY.labelLarge,
    color: COLORS.primary,
  },
  modalButtonFilled: {
    flex: 1,
    height: 48,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.primary,
    justifyContent: "center",
    alignItems: "center",
  },
  modalButtonFilledText: {
    fontFamily: "Inter_500Medium",
    ...TYPOGRAPHY.labelLarge,
    color: COLORS.onPrimary,
  },
  progressContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: SPACING.lg,
    gap: SPACING.md,
  },
  progressText: {
    fontFamily: "Inter_400Regular",
    ...TYPOGRAPHY.bodyMedium,
    color: COLORS.onSurfaceVariant,
    textAlign: "center",
    marginTop: SPACING.md,
  },
  shuffleButton: {
    position: "absolute",
    bottom: 22,
    right: SPACING.lg,
    width: 56,
    height: 56,
    borderRadius: RADIUS.lg,
    backgroundColor: COLORS.primary,
    justifyContent: "center",
    alignItems: "center",
    elevation: 6,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
  },
  shuffleButtonWithMiniPlayer: {
    bottom: 84,
  },
});
